services:
  spark-sandbox:
    image: spark:latest
    entrypoint: tail -f > /dev/null
    volumes:
      # Mount the README file so the container has some data to process.
      - ./README.md:/opt/spark/README.md
